/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yFrame;

import Class.Monitor;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author josue
 */
public class Monitores extends javax.swing.JFrame {
    private static ArrayList<Monitor> monitors = new ArrayList<>();
    
    public static ArrayList<Monitor> getmonitors() {
    return monitors;
}
    /**
     * Creates new form Monitores
     */
    public Monitores() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPHome2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jBMinimizar = new javax.swing.JButton();
        jBBackToinicio1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPHome2.setOpaque(false);
        jPHome2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("MONITORES");
        jPHome2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(111, 174, 2));
        jSeparator1.setForeground(new java.awt.Color(111, 174, 2));
        jPHome2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 850, 10));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/Acer_Nitro_Vg0_PcSoftware-1.png"))); // NOI18N
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 120, 140));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/monitor-gamer-27-aoc-monitor-gamer-27-aoc.png"))); // NOI18N
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 130, 140));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/png-transparent-playstation-3-wii-computer-monitors-benq-rl2240h-video-game-monitor-television-electronics-video-game.png"))); // NOI18N
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 120, 140));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("EN OFERTA");
        jPHome2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 67, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/MSI-Oculus-NXG251R (1).png"))); // NOI18N
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 120, 140));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/png-transparent-computer-monitors-freesync-displayport-1080p-refresh-rate-monitors-miscellaneous-television-electronics.png"))); // NOI18N
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 120, 140));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/monitor-gaming.png"))); // NOI18N
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 120, 140));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/MG278_00000.png"))); // NOI18N
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 130, 140));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/copy8806088600901_moni3.png"))); // NOI18N
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 120, 140));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/XB3_XB273U-NX_Standard_01.png"))); // NOI18N
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 120, 140));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/60ff26bfd4a0f-41dwr25nvbl-1600x1600.png"))); // NOI18N
        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 120, 140));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-7291398_1280 (1).png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPHome2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, 100, 40));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("$2980");
        jPHome2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 320, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-7291398_1280 (1).png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPHome2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 100, 40));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("$3400");
        jPHome2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("$120");
        jPHome2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-7291398_1280 (1).png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPHome2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 100, 40));

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("$1000");
        jPHome2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-7291398_1280 (1).png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPHome2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 100, 40));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-7291398_1280 (1).png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton5.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPHome2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 100, 40));

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("$990");
        jPHome2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-7291398_1280 (1).png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton6.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPHome2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 100, 40));

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("$350");
        jPHome2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-7291398_1280 (1).png"))); // NOI18N
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton10.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jPHome2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 100, 40));

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("$270");
        jPHome2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-7291398_1280 (1).png"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton11.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jPHome2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 100, 40));

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("$290");
        jPHome2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-7291398_1280 (1).png"))); // NOI18N
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton12.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jPHome2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 100, 40));

        jLabel11.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("$740");
        jPHome2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, -1, -1));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-7291398_1280 (1).png"))); // NOI18N
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton13.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jPHome2.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 100, 40));

        jLabel12.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("$720");
        jPHome2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, -1, -1));

        jBMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jBMinimizar.setBorder(null);
        jBMinimizar.setBorderPainted(false);
        jBMinimizar.setContentAreaFilled(false);
        jBMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBMinimizarMouseClicked(evt);
            }
        });
        jPHome2.add(jBMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 40, 40));

        jBBackToinicio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Home_32px.png"))); // NOI18N
        jBBackToinicio1.setBorder(null);
        jBBackToinicio1.setBorderPainted(false);
        jBBackToinicio1.setContentAreaFilled(false);
        jBBackToinicio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBBackToinicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBBackToinicio1MouseClicked(evt);
            }
        });
        jPHome2.add(jBBackToinicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 40, 40));

        getContentPane().add(jPHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Loginbueno.png"))); // NOI18N
        jPanel1.add(jlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBMinimizarMouseClicked
        this.setState(yFrame.Login.ICONIFIED);
    }//GEN-LAST:event_jBMinimizarMouseClicked

    private void jBBackToinicio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBackToinicio1MouseClicked
        Inicio inicio = new Inicio();
        dispose(); // Cierra la ventana de login
        inicio.setVisible(true);
    }//GEN-LAST:event_jBBackToinicio1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Monitor monitor1 = new Monitor(1, "Modelo 1_MO" ,350);
        monitors.add(monitor1);
        JOptionPane.showMessageDialog(null,"Se anadio correctamente el teclado modelo: " + monitor1.getNombre() + " al carrito de compras");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Monitor monitor2 = new Monitor(2, "Modelo 2_MO" ,270);
        monitors.add(monitor2);
        JOptionPane.showMessageDialog(null,"Se anadio correctamente el teclado modelo: " + monitor2.getNombre() + " al carrito de compras");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
       Monitor monitor3 = new Monitor(3, "Modelo 3_MO" ,290);
        monitors.add(monitor3);
        JOptionPane.showMessageDialog(null,"Se anadio correctamente el teclado modelo: " + monitor3.getNombre() + " al carrito de compras"); 
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        Monitor monitor4 = new Monitor(4, "Modelo 4_MO" ,740);
        monitors.add(monitor4);
        JOptionPane.showMessageDialog(null,"Se anadio correctamente el teclado modelo: " + monitor4.getNombre() + " al carrito de compras");
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        Monitor monitor5 = new Monitor(5, "Modelo 5_MO" ,720);
        monitors.add(monitor5);
        JOptionPane.showMessageDialog(null,"Se anadio correctamente el teclado modelo: " + monitor5.getNombre() + " al carrito de compras");
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        Monitor monitor6 = new Monitor(6, "Modelo 6_MO" ,990);
        monitors.add(monitor6);
        JOptionPane.showMessageDialog(null,"Se anadio correctamente el teclado modelo: " + monitor6.getNombre() + " al carrito de compras");
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        Monitor monitor7 = new Monitor(7, "Modelo 7_MO" ,1000);
        monitors.add(monitor7);
        JOptionPane.showMessageDialog(null,"Se anadio correctamente el teclado modelo: " + monitor7.getNombre() + " al carrito de compras");
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
     Monitor monitor8 = new Monitor(8, "Modelo 8_MO" ,120);
        monitors.add(monitor8);
        JOptionPane.showMessageDialog(null,"Se anadio correctamente el teclado modelo: " + monitor8.getNombre() + " al carrito de compras");
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        Monitor monitor9 = new Monitor(9, "Modelo 9_MO" ,3400);
        monitors.add(monitor9);
        JOptionPane.showMessageDialog(null,"Se anadio correctamente el teclado modelo: " + monitor9.getNombre() + " al carrito de compras");
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        Monitor monitor10 = new Monitor(10, "Modelo 10_MO" ,2980);
        monitors.add(monitor10);
        JOptionPane.showMessageDialog(null,"Se anadio correctamente el teclado modelo: " + monitor10.getNombre() + " al carrito de compras");
    }//GEN-LAST:event_jButton13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Monitores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Monitores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Monitores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Monitores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Monitores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBackToinicio1;
    private javax.swing.JButton jBMinimizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPHome2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlBackground;
    // End of variables declaration//GEN-END:variables
}
