/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yFrame;
import Class.Mouse;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author josue
 */
public class Mouses extends javax.swing.JFrame {
    private static ArrayList<Mouse> mouses = new ArrayList<>();
    
    public static ArrayList<Mouse> getMouses() {
    return mouses;
}

    /**
     * Creates new form Mouses
     */
    public Mouses() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPHome = new javax.swing.JPanel();
        jBMinimizar = new javax.swing.JButton();
        jBBackToinicio1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPHome.setOpaque(false);
        jPHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jBMinimizar.setBorder(null);
        jBMinimizar.setBorderPainted(false);
        jBMinimizar.setContentAreaFilled(false);
        jBMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBMinimizarMouseClicked(evt);
            }
        });
        jPHome.add(jBMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 40, 40));

        jBBackToinicio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Home_32px.png"))); // NOI18N
        jBBackToinicio1.setBorder(null);
        jBBackToinicio1.setBorderPainted(false);
        jBBackToinicio1.setContentAreaFilled(false);
        jBBackToinicio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBBackToinicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBBackToinicio1MouseClicked(evt);
            }
        });
        jPHome.add(jBBackToinicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 40, 40));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("MOUSES");
        jPHome.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(111, 174, 2));
        jSeparator1.setForeground(new java.awt.Color(111, 174, 2));
        jPHome.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 850, 10));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/mouse-gamer-redragon-storm-elite-blanco-rgb-m988w-rgb.png"))); // NOI18N
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 120, 140));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/614a49c8307475082d43e4c4.png"))); // NOI18N
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 130, 140));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/CENTROPHORUS.png"))); // NOI18N
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 120, 140));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("EN OFERTA");
        jPHome.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 67, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/images.png"))); // NOI18N
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 120, 140));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/Hipercentro-Electronico-mouse-gamer-con-luz-led-JYR-MGJR-043.png"))); // NOI18N
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 120, 140));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/g402-hyperion-fury-ultra-fast-fps-gaming-mouse.png"))); // NOI18N
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 149, 120, 140));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/910-003879.png"))); // NOI18N
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 149, 130, 140));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/Mouse-Gamer-G502-X-Plus-Black-3.png"))); // NOI18N
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 149, 120, 140));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/mouse-gamer-war-2_211-720d429e3b20fd449a16915256931926-1024-1024.png"))); // NOI18N
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 149, 120, 140));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/Sin-titulo-2-42.png"))); // NOI18N
        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 149, 120, 140));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-7291398_1280 (1).png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPHome.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, 100, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-7291398_1280 (1).png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPHome.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 100, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-7291398_1280 (1).png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPHome.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 100, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-7291398_1280 (1).png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPHome.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 100, 40));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-7291398_1280 (1).png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton5.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPHome.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 100, 40));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-7291398_1280 (1).png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton6.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPHome.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 100, 40));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-7291398_1280 (1).png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton7.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPHome.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 100, 40));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-7291398_1280 (1).png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton8.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jPHome.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 100, 40));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-7291398_1280 (1).png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton9.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jPHome.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 100, 40));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-7291398_1280 (1).png"))); // NOI18N
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton10.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/StoreImages/shop-kiwi-green-on (1).png"))); // NOI18N
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jPHome.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 100, 40));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("$98");
        jPHome.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("$330");
        jPHome.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("$290");
        jPHome.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("$120");
        jPHome.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("$65");
        jPHome.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("$110");
        jPHome.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("$210");
        jPHome.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("$106");
        jPHome.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("$27");
        jPHome.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("$100");
        jPHome.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, -1, -1));

        getContentPane().add(jPHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Loginbueno.png"))); // NOI18N
        jPanel1.add(jlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBMinimizarMouseClicked
        this.setState(yFrame.Login.ICONIFIED);
    }//GEN-LAST:event_jBMinimizarMouseClicked

    private void jBBackToinicio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBackToinicio1MouseClicked
        Inicio inicio = new Inicio();
        dispose(); // Cierra la ventana de login
        inicio.setVisible(true);
    }//GEN-LAST:event_jBBackToinicio1MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        Mouse mouse1 = new Mouse(1, "Modelo 1_M" ,110);
        mouses.add(mouse1);
        JOptionPane.showMessageDialog(null,"Se anadio correctamente el mouse modelo: " + mouse1.getNombre() + " al carrito de compras");
        
        
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        Mouse mouse2 = new Mouse(2, "Modelo 2_M" ,98);
        mouses.add(mouse2);
        JOptionPane.showMessageDialog(null,"Se anadio correctamente el mouse modelo: " + mouse2.getNombre() + " al carrito de compras");
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        Mouse mouse3 = new Mouse(3, "Modelo 3_M" ,120);
        mouses.add(mouse3);
        JOptionPane.showMessageDialog(null,"Se anadio correctamente el mouse modelo: " + mouse3.getNombre() + " al carrito de compras");
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        Mouse mouse4 = new Mouse(4, "Modelo 4_M" ,65);
        mouses.add(mouse4);
        JOptionPane.showMessageDialog(null,"Se anadio correctamente el mouse modelo: " + mouse4.getNombre() + " al carrito de compras");
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Mouse mouse5 = new Mouse(5, "Modelo 5_M" ,330);
        mouses.add(mouse5);
        JOptionPane.showMessageDialog(null,"Se anadio correctamente el mouse modelo: " + mouse5.getNombre() + " al carrito de compras");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        Mouse mouse6 = new Mouse(6, "Modelo 6_M" ,210);
        mouses.add(mouse6);
        JOptionPane.showMessageDialog(null,"Se anadio correctamente el mouse modelo: " + mouse6.getNombre() + " al carrito de compras");
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Mouse mouse7 = new Mouse(7, "Modelo 7_M" ,106);
        mouses.add(mouse7);
        JOptionPane.showMessageDialog(null,"Se anadio correctamente el mouse modelo: " + mouse7.getNombre() + " al carrito de compras");
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        Mouse mouse8 = new Mouse(8, "Modelo 8_M" ,27);
        mouses.add(mouse8);
        JOptionPane.showMessageDialog(null,"Se anadio correctamente el mouse modelo: " + mouse8.getNombre() + " al carrito de compras");
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        Mouse mouse9 = new Mouse(9, "Modelo 9_M" ,100);
        mouses.add(mouse9);
        JOptionPane.showMessageDialog(null,"Se anadio correctamente el mouse modelo: " + mouse9.getNombre() + " al carrito de compras");
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Mouse mouse10 = new Mouse(10, "Modelo 10_M" ,290);
        mouses.add(mouse10);
        JOptionPane.showMessageDialog(null,"Se anadio correctamente el mouse modelo: " + mouse10.getNombre() + " al carrito de compras");
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mouses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mouses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mouses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mouses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mouses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBackToinicio1;
    private javax.swing.JButton jBMinimizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPHome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlBackground;
    // End of variables declaration//GEN-END:variables
}
